"""empty message

Revision ID: 9d28546674e3
Revises: 026f828a4ddd
Create Date: 2022-07-24 20:19:04.133090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d28546674e3'
down_revision = '026f828a4ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('description', sa.String(length=1500), nullable=True))
    op.add_column('venues', sa.Column('description', sa.String(length=1500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'description')
    op.drop_column('artists', 'description')
    # ### end Alembic commands ###
